import { useRef, useMemo, useEffect, useCallback } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { RigidBody, CapsuleCollider, useRapier, interactionGroups } from "@react-three/rapier";
import * as THREE from "three";
import {
  CAM_DIST_DEFAULT,
  CAM_DIST_MIN,
  CAM_DIST_MAX,
  MOUSE_SENS,
  PITCH_MIN,
  PITCH_MAX,
} from "../controls.js";
import { damagePerSecond } from "../wallMaterials.js";
import { GROUP_PLAYER, PLAYER_FILTER } from "../collisionGroups.js";

/**
 * Third-person physics player for "Laser Escape".
 *
 * The visible character is the rigged mesh exported from World.blend
 * (public/player.glb). It is driven by an invisible dynamic capsule:
 * physics moves the capsule, the model is snapped to it each frame and
 * yawed toward the movement direction.
 *
 * Controls:
 *  - WASD / arrows  move (relative to the camera), Space jumps
 *  - right-mouse drag  orbits the camera around the player
 *  - mouse wheel  zooms the camera in / out
 *  - hold left click  fires a continuous laser at whatever is under the
 *    cursor in 3D (release to let it fade)
 * The OS cursor stays visible the whole time (no pointer lock).
 *
 * player.glb has no locomotion clips (only a T-pose), so the walk cycle is
 * generated procedurally: a set of CC-rig bones are rotated each frame by a
 * `gait` factor that eases 0..1 with speed. Idle just drops the arms.
 *
 * The only things that cross the component boundary are `onTargetHit(targetId)`
 * and `controls`, the shared input object from src/controls.js: keyboard/mouse
 * listeners here and the on-screen touch controls (TouchControls.jsx) both
 * write into it, this component only reads it each frame. Targets are meshes
 * tagged `userData.isTarget = true` (optionally `userData.targetId`); the
 * laser mesh-raycasts only that array, and uses a cheap physics ray for the
 * beam's end point on a miss.
 */

const SPEED = 5;
const JUMP_SPEED = 5.5;
const CAPSULE_RADIUS = 0.3;
const CAPSULE_HALF_HEIGHT = 0.6; // cylinder half-height (~1.8 total)
const FOOT_OFFSET = CAPSULE_HALF_HEIGHT + CAPSULE_RADIUS; // centre -> feet

const MODEL_TARGET_HEIGHT = 1.7; // normalize the glb to this many metres
const PLAYER_SCALE = 2.1; // extra shrink applied on top of the height-normalized fit
// Loose sanity clamp on the normalised scale: only there to stop a degenerate
// measurement from filling the screen or vanishing. player.glb needs ~0.27x;
// a conventionally-scaled glb would be ~1x -- both sit comfortably inside.
const MODEL_SCALE_MIN = 0.02;
const MODEL_SCALE_MAX = 20;
const MODEL_FACING = 0; // yaw added so the model faces its travel dir

const CAM_ZOOM_RATE = 0.0016; // wheel deltaY -> fraction of current distance
const CAM_LOOK_HEIGHT = 1.5; // look point above the feet
const CAM_MIN_DIST = 1.0; // don't let wall-collision push closer than this

const LASER_RANGE = 80;
const BEAM_MS = 130;
const MUZZLE_HEIGHT = 1.5; // beam origin above the feet

// player.glb ships with no locomotion clips (only a T-pose), so the walk /
// run cycle is generated by rotating these CC-rig bones in useFrame.
const GAIT_BONES = [
  "CC_Base_L_Upperarm",
  "CC_Base_R_Upperarm",
  "CC_Base_L_Forearm",
  "CC_Base_R_Forearm",
  "CC_Base_L_Thigh",
  "CC_Base_R_Thigh",
  "CC_Base_L_Calf",
  "CC_Base_R_Calf",
  "CC_Base_Spine02",
];
const ARM_DOWN = 1.2; // rad: drop the arms from the T-pose to the sides

const WORLD_UP = new THREE.Vector3(0, 1, 0);
const GEO_UP = new THREE.Vector3(0, 1, 0);
const RAY_DOWN = { x: 0, y: -1, z: 0 };
const _q = new THREE.Quaternion();
const _e = new THREE.Euler();

const KEYMAP = {
  KeyW: "forward",
  ArrowUp: "forward",
  KeyS: "back",
  ArrowDown: "back",
  KeyA: "left",
  ArrowLeft: "left",
  KeyD: "right",
  ArrowRight: "right",
  Space: "jump",
};

function lerpAngle(a, b, t) {
  let d = ((b - a + Math.PI) % (Math.PI * 2)) - Math.PI;
  if (d < -Math.PI) d += Math.PI * 2;
  return a + d * t;
}

export default function Player({
  spawnPosition = [0, 2, 0],
  onTargetHit,
  controls,
  wallHealth,
}) {
  const body = useRef(null); // RapierRigidBody
  const rig = useRef(null); // group holding the model, snapped to the capsule
  const beam = useRef(null); // reused world-space beam mesh

  const { camera, gl, scene } = useThree();
  const { world, rapier } = useRapier();

  // --- character model ------------------------------------------------------
  // Single player instance -> use the loaded scene directly. The per-frame
  // bone posing mutates it in place; a hot-reload of this file can leave the
  // pose stale until a full page refresh (dev-only).
  const gltf = useGLTF("/player.glb");
  const model = gltf.scene;

  const inner = useRef(null); // scaled group (also bobs vertically while walking)
  const bones = useRef({}); // name -> THREE.Bone
  const rest = useRef({}); // name -> bind-pose quaternion
  const phase = useRef(0); // walk-cycle phase
  const gait = useRef(0); // 0 idle .. 1 full-speed, eased

  // Height-normalise the model to MODEL_TARGET_HEIGHT.
  //
  // Measure it *detached from its parent*: the model is rendered inside a group
  // that carries `fit.scale`, so measuring it in place feeds the previous
  // frame's scale back into the box and the value never settles. In `npm run
  // dev` the timing happened to converge near the right number; a production
  // build read a matrixWorld still carrying a stale scale and the character
  // came out huge. Nulling `model.parent` for the measurement (restored in the
  // same synchronous pass, before React commits) breaks that feedback loop and
  // removes any dependence on render/commit timing.
  const fit = useMemo(() => {
    const parent = model.parent;
    model.parent = null;
    model.updateWorldMatrix(false, true);
    const box = new THREE.Box3().setFromObject(model);
    model.parent = parent;
    model.updateWorldMatrix(true, true);

    if (box.isEmpty()) return { scale: 1, y: -FOOT_OFFSET };
    const size = box.getSize(new THREE.Vector3());
    const raw = MODEL_TARGET_HEIGHT / (size.y || 1);
    const s =
      THREE.MathUtils.clamp(
        Number.isFinite(raw) ? raw : 1,
        MODEL_SCALE_MIN,
        MODEL_SCALE_MAX,
      ) * PLAYER_SCALE;
    if (
      import.meta.env.DEV &&
      (!Number.isFinite(raw) || raw < MODEL_SCALE_MIN || raw > MODEL_SCALE_MAX)
    ) {
      // eslint-disable-next-line no-console
      console.warn(
        `[Player] implausible fit scale ${raw} (size.y=${size.y}); clamped to ${s}`,
      );
    }
    const y = -FOOT_OFFSET - box.min.y * s; // lowest point sits at the feet
    return { scale: s, y };
  }, [model]);

  useEffect(() => {
    bones.current = {};
    rest.current = {};
    model.traverse((o) => {
      if (o.isMesh || o.isSkinnedMesh) {
        o.castShadow = true;
        o.frustumCulled = false;
      }
      if (o.isBone && GAIT_BONES.includes(o.name)) {
        bones.current[o.name] = o;
        rest.current[o.name] = o.quaternion.clone();
      }
    });
  }, [model]);

  // Rotate a bone by (x,y,z) euler radians on top of its bind pose.
  const poseBone = useCallback((name, x, y, z) => {
    const b = bones.current[name];
    const r = rest.current[name];
    if (!b || !r) return;
    _e.set(x, y, z);
    _q.setFromEuler(_e);
    b.quaternion.copy(r).multiply(_q);
  }, []);

  // --- input ---------------------------------------------------------------
  // `controls` is a shared mutable object (src/controls.js): keyboard/mouse
  // (below) and the touch overlay both write into it, this component only
  // reads it (aside from its own keyboard/mouse listeners).
  const modelYaw = useRef(0);
  const camDist = useRef(CAM_DIST_DEFAULT); // eased toward controls.camDistTarget
  const orbiting = useRef(false); // right mouse button held

  const targets = useRef([]);
  const walls = useRef([]);
  const heldHitId = useRef(null); // target currently under the held beam
  const beamState = useRef({
    held: false,
    releaseT0: 0,
    from: new THREE.Vector3(),
    to: new THREE.Vector3(),
  });
  const raycaster = useMemo(() => new THREE.Raycaster(), []);

  const tmp = useMemo(
    () => ({
      pos: new THREE.Vector3(),
      look: new THREE.Vector3(),
      offset: new THREE.Vector3(),
      cam: new THREE.Vector3(),
      fwd: new THREE.Vector3(),
      right: new THREE.Vector3(),
      wish: new THREE.Vector3(),
      dir: new THREE.Vector3(),
      mid: new THREE.Vector3(),
      origin: new THREE.Vector3(),
    }),
    [],
  );

  // --- keyboard ----------------------------------------------------------------
  // Tracks raw key state so releasing one of two opposite keys (e.g. still
  // holding D after tapping A) doesn't zero out movement.
  const keys = useRef({ forward: false, back: false, left: false, right: false });
  useEffect(() => {
    const applyMove = () => {
      const k = keys.current;
      controls.move.z = (k.forward ? 1 : 0) - (k.back ? 1 : 0);
      controls.move.x = (k.right ? 1 : 0) - (k.left ? 1 : 0);
    };
    const set = (code, v) => {
      const k = KEYMAP[code];
      if (!k) return;
      if (k === "jump") controls.jump = v;
      else {
        keys.current[k] = v;
        applyMove();
      }
    };
    const down = (e) => set(e.code, true);
    const up = (e) => set(e.code, false);
    const clear = () => {
      for (const k in keys.current) keys.current[k] = false;
      controls.jump = false;
      applyMove();
    };
    window.addEventListener("keydown", down);
    window.addEventListener("keyup", up);
    window.addEventListener("blur", clear);
    return () => {
      window.removeEventListener("keydown", down);
      window.removeEventListener("keyup", up);
      window.removeEventListener("blur", clear);
    };
  }, [controls]);

  // --- camera orbit (right-drag) + zoom (wheel), cursor stays visible ------
  useEffect(() => {
    const el = gl.domElement;
    el.style.cursor = "crosshair";

    const onContextMenu = (e) => e.preventDefault(); // right-drag, not a menu
    const onPointerDown = (e) => {
      if (e.pointerType === "touch") return; // touch look is handled by TouchControls
      if (e.button === 2) {
        orbiting.current = true;
        e.preventDefault();
      }
    };
    const onPointerUp = (e) => {
      if (e.button === 2) orbiting.current = false;
    };
    const onMove = (e) => {
      if (e.pointerType === "touch" || !orbiting.current) return;
      controls.yaw -= e.movementX * MOUSE_SENS;
      controls.pitch = THREE.MathUtils.clamp(
        controls.pitch + e.movementY * MOUSE_SENS,
        PITCH_MIN,
        PITCH_MAX,
      );
    };
    const onWheel = (e) => {
      e.preventDefault();
      controls.camDistTarget = THREE.MathUtils.clamp(
        controls.camDistTarget + e.deltaY * CAM_ZOOM_RATE * controls.camDistTarget,
        CAM_DIST_MIN,
        CAM_DIST_MAX,
      );
    };
    const onBlur = () => {
      orbiting.current = false;
    };

    el.addEventListener("contextmenu", onContextMenu);
    el.addEventListener("pointerdown", onPointerDown);
    el.addEventListener("wheel", onWheel, { passive: false });
    window.addEventListener("pointerup", onPointerUp);
    window.addEventListener("pointermove", onMove);
    window.addEventListener("blur", onBlur);
    return () => {
      el.removeEventListener("contextmenu", onContextMenu);
      el.removeEventListener("pointerdown", onPointerDown);
      el.removeEventListener("wheel", onWheel);
      window.removeEventListener("pointerup", onPointerUp);
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("blur", onBlur);
    };
  }, [gl, controls]);

  // --- target array from userData tags ------------------------------------
  const collect = useCallback(() => {
    const t = [];
    const w = [];
    scene.traverse((o) => {
      if (o.userData?.isTarget) t.push(o);
      else if (o.userData?.isWall) w.push(o);
    });
    targets.current = t;
    walls.current = w;
  }, [scene]);
  useEffect(() => {
    collect();
  }, [collect]);

  const resolveTarget = (obj) => {
    let o = obj;
    while (o) {
      if (o.userData?.isTarget) return o;
      o = o.parent;
    }
    return null;
  };

  // Cast the beam from the muzzle toward the screen point (NDC -1..1),
  // writing beamState.from/to. When `trigger`, notify a target the first
  // frame the beam lands on it (re-notifies if it sweeps onto a new one).
  const castBeam = useCallback(
    (ndcX, ndcY, trigger, dt) => {
      const rb = body.current;
      if (!rb) return;

      raycaster.setFromCamera({ x: ndcX, y: ndcY }, camera);
      raycaster.far = LASER_RANGE;
      const origin = raycaster.ray.origin;
      tmp.dir.copy(raycaster.ray.direction);
      collect();

      const tHit = raycaster.intersectObjects(targets.current, true)[0];
      const wMeshHit = raycaster.intersectObjects(walls.current, true)[0];

      const rray = new rapier.Ray(origin, tmp.dir);
      const wHit = world.castRay(
        rray,
        LASER_RANGE,
        true,
        undefined,
        undefined,
        undefined,
        rb,
      );
      const wallToi = wHit ? wHit.timeOfImpact : Infinity;

      // The wall mesh raycast should land ~on top of the physics wallToi when
      // the beam is genuinely striking that wall's surface (it's the same
      // geometry); a small epsilon absorbs mesh-vs-collider fitting error.
      const wallHitValid = wMeshHit && wMeshHit.distance <= wallToi + 0.05;

      const to = beamState.current.to;
      let hitTarget = null;
      let hitWall = null;
      if (tHit && tHit.distance <= wallToi) {
        to.copy(tHit.point);
        hitTarget = resolveTarget(tHit.object);
      } else if (wallHitValid) {
        to.copy(wMeshHit.point);
        hitWall = wMeshHit.object;
      } else if (wHit) {
        to.copy(origin).addScaledVector(tmp.dir, wallToi);
      } else {
        to.copy(origin).addScaledVector(tmp.dir, LASER_RANGE);
      }

      const t = rb.translation();
      beamState.current.from.set(
        t.x,
        t.y - CAPSULE_HALF_HEIGHT + MUZZLE_HEIGHT,
        t.z,
      );

      const id = hitTarget
        ? (hitTarget.userData.targetId ?? hitTarget.name ?? hitTarget.uuid)
        : null;
      if (trigger && id && id !== heldHitId.current) {
        hitTarget.userData.onHit?.(id);
        onTargetHit?.(id);
      }
      if (trigger) heldHitId.current = id;

      if (trigger && hitWall && dt && wallHealth) {
        const { wallType, strength } = hitWall.userData;
        const entry = wallHealth.get(wallType);
        if (entry && entry.hp > 0) {
          entry.hp = Math.max(0, entry.hp - damagePerSecond(strength) * dt);
        }
      }
    },
    [camera, raycaster, tmp, world, rapier, collect, onTargetHit, wallHealth],
  );

  // Left button held -> keep firing; release -> let the beam fade.
  // Touch fire is handled entirely by TouchControls (button + centered aim),
  // so touch pointer events here are ignored to avoid firing on every tap.
  useEffect(() => {
    const el = gl.domElement;
    const ndc = (e) => {
      const r = el.getBoundingClientRect();
      controls.aim.x = ((e.clientX - r.left) / r.width) * 2 - 1;
      controls.aim.y = -((e.clientY - r.top) / r.height) * 2 + 1;
    };
    const onDown = (e) => {
      if (e.pointerType === "touch" || e.button !== 0) return; // left only; right is orbit
      ndc(e);
      controls.firing = true;
      beamState.current.held = true;
      heldHitId.current = null;
    };
    const onMove = (e) => {
      if (e.pointerType === "touch") return;
      ndc(e);
    };
    const stop = () => {
      if (!controls.firing) return;
      controls.firing = false;
      beamState.current.held = false;
      beamState.current.releaseT0 = performance.now();
      heldHitId.current = null;
    };
    const onUp = (e) => {
      if (e.pointerType === "touch") return;
      if (e.button === 0) stop();
    };
    el.addEventListener("pointerdown", onDown);
    el.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
    window.addEventListener("blur", stop);
    return () => {
      el.removeEventListener("pointerdown", onDown);
      el.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
      window.removeEventListener("blur", stop);
    };
  }, [castBeam, gl, controls]);

  // --- per-frame ---------------------------------------------------------
  useFrame((_, dt) => {
    const rb = body.current;
    if (!rb) return;
    const step = Math.min(dt, 0.05);

    const t = rb.translation();
    tmp.pos.set(t.x, t.y, t.z);

    // Camera basis: forward is where the camera looks, flattened to XZ.
    camDist.current = THREE.MathUtils.damp(
      camDist.current,
      controls.camDistTarget,
      12,
      step,
    );
    const cy = controls.yaw;
    const cp = controls.pitch;
    tmp.offset
      .set(
        Math.sin(cy) * Math.cos(cp),
        Math.sin(cp),
        Math.cos(cy) * Math.cos(cp),
      )
      .multiplyScalar(camDist.current);
    tmp.look.copy(tmp.pos).addScaledVector(WORLD_UP, CAM_LOOK_HEIGHT - FOOT_OFFSET);
    tmp.cam.copy(tmp.look).add(tmp.offset);

    // Pull the camera in if a wall is between it and the player.
    tmp.dir.copy(tmp.cam).sub(tmp.look);
    const want = tmp.dir.length();
    tmp.dir.normalize();
    const camRay = new rapier.Ray(tmp.look, tmp.dir);
    const camHit = world.castRay(
      camRay,
      want,
      false,
      undefined,
      undefined,
      undefined,
      rb,
    );
    // Only pull in for a genuine obstruction; a tiny toi means the look point
    // is grazing / inside geometry, so keep the full distance instead.
    let dist = want;
    if (camHit && camHit.timeOfImpact > 0.4 && camHit.timeOfImpact < want) {
      dist = Math.max(CAM_MIN_DIST, camHit.timeOfImpact - 0.2);
    }
    camera.position.copy(tmp.look).addScaledVector(tmp.dir, dist);
    camera.lookAt(tmp.look);

    // Movement direction from camera yaw only.
    tmp.fwd.copy(tmp.look).sub(tmp.cam);
    tmp.fwd.y = 0;
    if (tmp.fwd.lengthSq() < 1e-6) tmp.fwd.set(0, 0, -1);
    tmp.fwd.normalize();
    tmp.right.crossVectors(tmp.fwd, WORLD_UP).normalize();

    const mz = controls.move.z;
    const mx = controls.move.x;
    tmp.wish
      .set(0, 0, 0)
      .addScaledVector(tmp.fwd, mz)
      .addScaledVector(tmp.right, mx);
    // Clamp (not normalize) so analog joystick input under full deflection
    // moves slower, while keyboard's unit/diagonal vectors behave as before.
    const wishLen = tmp.wish.length();
    const moving = wishLen > 0.001;
    if (moving) tmp.wish.multiplyScalar((Math.min(wishLen, 1) / wishLen) * SPEED);

    const v = rb.linvel();
    rb.setLinvel({ x: tmp.wish.x, y: v.y, z: tmp.wish.z }, true);

    // Grounded check + jump.
    tmp.origin.set(t.x, t.y, t.z);
    const groundHit = world.castRay(
      new rapier.Ray(tmp.origin, RAY_DOWN),
      FOOT_OFFSET + 0.15,
      true,
      undefined,
      undefined,
      undefined,
      rb,
    );
    const grounded = groundHit != null;
    if (controls.jump && grounded && v.y <= 0.1) {
      rb.setLinvel({ x: v.x, y: JUMP_SPEED, z: v.z }, true);
    }

    // Snap the model to the capsule; yaw it toward travel direction.
    if (rig.current) {
      rig.current.position.copy(tmp.pos);
      if (moving) {
        const target = Math.atan2(tmp.wish.x, tmp.wish.z) + MODEL_FACING;
        modelYaw.current = lerpAngle(modelYaw.current, target, 1 - Math.pow(0.001, step));
      }
      rig.current.rotation.y = modelYaw.current;
    }

    // Procedural walk cycle (no clips in the glb). gait eases 0..1 with speed;
    // phase only advances while actually moving.
    const wishSpeed = Math.hypot(tmp.wish.x, tmp.wish.z);
    gait.current = THREE.MathUtils.damp(
      gait.current,
      THREE.MathUtils.clamp(wishSpeed / SPEED, 0, 1),
      10,
      step,
    );
    const g = gait.current;
    if (g > 0.005) phase.current += step * (7 + 3 * g);
    const sw = Math.sin(phase.current);
    const cw = Math.cos(phase.current);

    // arms drop to the sides (even idle) and swing opposite the legs
    poseBone("CC_Base_L_Upperarm", 0, 0, -ARM_DOWN - 0.4 * sw * g);
    poseBone("CC_Base_R_Upperarm", 0, 0, ARM_DOWN - 0.4 * sw * g);
    poseBone("CC_Base_L_Forearm", 0.6 * g * (0.5 - 0.5 * cw), 0, 0);
    poseBone("CC_Base_R_Forearm", 0.6 * g * (0.5 + 0.5 * cw), 0, 0);
    // thighs swing fore/aft, calves tuck on the rear swing
    poseBone("CC_Base_L_Thigh", 0.6 * sw * g, 0, 0);
    poseBone("CC_Base_R_Thigh", -0.6 * sw * g, 0, 0);
    poseBone("CC_Base_L_Calf", Math.max(0, -0.95 * sw) * g, 0, 0);
    poseBone("CC_Base_R_Calf", Math.max(0, 0.95 * sw) * g, 0, 0);
    // subtle torso twist + vertical bob
    poseBone("CC_Base_Spine02", 0.06 * g, -0.12 * sw * g, 0);
    if (inner.current) {
      inner.current.position.y = fit.y + Math.abs(sw) * 0.04 * g;
    }

    // Laser beam: continuous while the button is held, then a short fade.
    const bs = beamState.current;
    const mesh = beam.current;
    if (mesh) {
      const drawBeam = (opacity) => {
        const len = bs.from.distanceTo(bs.to);
        tmp.mid.copy(bs.from).add(bs.to).multiplyScalar(0.5);
        tmp.dir.copy(bs.to).sub(bs.from).normalize();
        mesh.position.copy(tmp.mid);
        mesh.quaternion.setFromUnitVectors(GEO_UP, tmp.dir);
        mesh.scale.set(1, Math.max(len, 0.001), 1);
        mesh.material.opacity = opacity;
        mesh.visible = true;
      };
      if (controls.firing) {
        castBeam(controls.aim.x, controls.aim.y, true, step);
        drawBeam(0.8 + 0.2 * Math.sin(performance.now() * 0.05)); // hum
      } else if (bs.releaseT0) {
        const age = performance.now() - bs.releaseT0;
        if (age >= BEAM_MS) {
          bs.releaseT0 = 0;
          mesh.visible = false;
        } else {
          drawBeam(1 - age / BEAM_MS);
        }
      } else {
        mesh.visible = false;
      }
    }
  });

  return (
    <>
      <RigidBody
        ref={body}
        type="dynamic"
        colliders={false}
        position={spawnPosition}
        enabledRotations={[false, false, false]}
        ccd
        mass={1}
        friction={0}
        restitution={0}
        linearDamping={0}
        canSleep={false}
      >
        <CapsuleCollider
          args={[CAPSULE_HALF_HEIGHT, CAPSULE_RADIUS]}
          collisionGroups={interactionGroups(GROUP_PLAYER, PLAYER_FILTER)}
        />
      </RigidBody>

      {/* visible character, snapped to the capsule every frame */}
      <group ref={rig}>
        <group ref={inner} scale={fit.scale} position={[0, fit.y, 0]}>
          <primitive object={model} />
        </group>
      </group>

      {/* reused world-space laser beam */}
      <mesh ref={beam} visible={false} frustumCulled={false}>
        <cylinderGeometry args={[0.02, 0.02, 1, 8, 1, true]} />
        <meshBasicMaterial
          color="#ff2d55"
          transparent
          opacity={0}
          toneMapped={false}
          depthWrite={false}
        />
      </mesh>
    </>
  );
}

useGLTF.preload("/player.glb");
