import * as THREE from "three";
import { SkeletonUtils } from "three-stdlib";
import { flattenMaterial } from "./flattenMaterial.js";

/**
 * Everything about how player.glb is fitted/scaled/posed, shared between the
 * local physics-driven Player.jsx and the network-driven RemotePlayer.jsx so
 * neither has to duplicate the other's model logic.
 */

export const SPEED = 8;
export const BASE_SPEED = 5; // SPEED the procedural gait cycle below was tuned at
export const CAPSULE_RADIUS = 0.3;
export const CAPSULE_HALF_HEIGHT = 0.6; // cylinder half-height (~1.8 total)
export const FOOT_OFFSET = CAPSULE_HALF_HEIGHT + CAPSULE_RADIUS; // centre -> feet

export const MODEL_TARGET_HEIGHT = 1.7; // normalize the glb to this many metres
export const PLAYER_SCALE = 2.1; // extra shrink applied on top of the height-normalized fit
// Loose sanity clamp on the normalised scale: only there to stop a degenerate
// measurement from filling the screen or vanishing. player.glb needs ~0.27x;
// a conventionally-scaled glb would be ~1x -- both sit comfortably inside.
export const MODEL_SCALE_MIN = 0.02;
export const MODEL_SCALE_MAX = 20;
export const MODEL_FACING = 0; // yaw added so the model faces its travel dir

export const MUZZLE_HEIGHT = 1.5; // beam origin above the feet

// player.glb ships with no locomotion clips (only a T-pose), so the walk /
// run cycle is generated by rotating these CC-rig bones in useFrame.
export const GAIT_BONES = [
  "CC_Base_L_Upperarm",
  "CC_Base_R_Upperarm",
  "CC_Base_L_Forearm",
  "CC_Base_R_Forearm",
  "CC_Base_L_Thigh",
  "CC_Base_R_Thigh",
  "CC_Base_L_Calf",
  "CC_Base_R_Calf",
  "CC_Base_Spine02",
];
export const ARM_DOWN = 1.2; // rad: drop the arms from the T-pose to the sides

// Running-gait amplitudes (rad unless noted). Bigger than a walk cycle would
// use: a sprint drives the arms and knees through a much wider range and
// leans the torso into the direction of travel.
export const RUN_ARM_SWING = 0.7; // upper-arm fore/aft pump
export const RUN_FOREARM_BEND = 0.9; // elbow bend range
export const RUN_THIGH_SWING = 0.8; // hip fore/aft
export const RUN_CALF_TUCK = 1.1; // knee bend on the recovery swing
export const RUN_SPINE_ARCH = 0.08;
export const RUN_SPINE_TWIST = 0.14;
export const RUN_LEAN_MAX = 0.16; // forward torso lean at full gait
export const RUN_BOB_AMP = 0.06; // vertical bounce

const _q = new THREE.Quaternion();
const _e = new THREE.Euler();

export function lerpAngle(a, b, t) {
  let d = ((b - a + Math.PI) % (Math.PI * 2)) - Math.PI;
  if (d < -Math.PI) d += Math.PI * 2;
  return a + d * t;
}

/**
 * A dedicated skinned-mesh clone for each remote player -- player.glb's
 * loaded scene is otherwise a single shared instance (Player.jsx relies on
 * that for the local player), so every remote needs its own independently
 * posable copy.
 */
export function cloneCharacterModel(scene) {
  return SkeletonUtils.clone(scene);
}

/**
 * Height-normalise the model to MODEL_TARGET_HEIGHT.
 *
 * Measure it *detached from its parent*: the model is rendered inside a group
 * that carries `fit.scale`, so measuring it in place feeds the previous
 * frame's scale back into the box and the value never settles. Nulling
 * `model.parent` for the measurement (restored in the same synchronous pass)
 * breaks that feedback loop and removes any dependence on render/commit
 * timing.
 */
export function computeModelFit(model) {
  const parent = model.parent;
  model.parent = null;
  model.updateWorldMatrix(false, true);
  const box = new THREE.Box3().setFromObject(model);
  model.parent = parent;
  model.updateWorldMatrix(true, true);

  if (box.isEmpty()) return { scale: 1, y: -FOOT_OFFSET };
  const size = box.getSize(new THREE.Vector3());
  const raw = MODEL_TARGET_HEIGHT / (size.y || 1);
  const s =
    THREE.MathUtils.clamp(Number.isFinite(raw) ? raw : 1, MODEL_SCALE_MIN, MODEL_SCALE_MAX) *
    PLAYER_SCALE;
  if (
    import.meta.env.DEV &&
    (!Number.isFinite(raw) || raw < MODEL_SCALE_MIN || raw > MODEL_SCALE_MAX)
  ) {
    // eslint-disable-next-line no-console
    console.warn(`[playerModel] implausible fit scale ${raw} (size.y=${size.y}); clamped to ${s}`);
  }
  const y = -FOOT_OFFSET - box.min.y * s; // lowest point sits at the feet
  return { scale: s, y };
}

/** Traverse the model, set up shadow/frustum/material flags, and collect the gait bones + their bind-pose quaternions. */
export function collectGaitBones(model) {
  const bones = {};
  const rest = {};
  model.traverse((o) => {
    if (o.isMesh || o.isSkinnedMesh) {
      o.castShadow = true;
      o.frustumCulled = false;
      flattenMaterial(o.material);
    }
    if (o.isBone && GAIT_BONES.includes(o.name)) {
      bones[o.name] = o;
      rest[o.name] = o.quaternion.clone();
    }
  });
  return { bones, rest };
}

/** Returns a poseBone(name, x, y, z) closure that rotates a bone by euler radians on top of its bind pose. */
export function makePoseBone(bones, rest) {
  return (name, x, y, z) => {
    const b = bones[name];
    const r = rest[name];
    if (!b || !r) return;
    _e.set(x, y, z);
    _q.setFromEuler(_e);
    b.quaternion.copy(r).multiply(_q);
  };
}

/**
 * Advances the eased gait amplitude toward `speed01` (0 idle .. 1 full-speed)
 * and the walk-cycle phase, mutating `gaitRef`/`phaseRef` in place. Returns
 * the updated gait amplitude for convenience.
 */
export function advanceGaitPhase(phaseRef, gaitRef, speed01, dt) {
  gaitRef.current = THREE.MathUtils.damp(gaitRef.current, THREE.MathUtils.clamp(speed01, 0, 1), 10, dt);
  const g = gaitRef.current;
  if (g > 0.005) phaseRef.current += dt * (7 + 3 * g) * (SPEED / BASE_SPEED);
  return g;
}

/** Applies one frame of the procedural run-cycle pose given a phase and eased gait amplitude. */
export function applyGaitPose(poseBone, phase, gait) {
  const sw = Math.sin(phase);
  const cw = Math.cos(phase);

  // arms drop to the sides (even idle) and pump opposite the legs
  poseBone("CC_Base_L_Upperarm", 0, 0, -ARM_DOWN - RUN_ARM_SWING * sw * gait);
  poseBone("CC_Base_R_Upperarm", 0, 0, ARM_DOWN - RUN_ARM_SWING * sw * gait);
  poseBone("CC_Base_L_Forearm", RUN_FOREARM_BEND * gait * (0.5 - 0.5 * cw), 0, 0);
  poseBone("CC_Base_R_Forearm", RUN_FOREARM_BEND * gait * (0.5 + 0.5 * cw), 0, 0);
  // thighs drive fore/aft, calves tuck high on the recovery swing
  poseBone("CC_Base_L_Thigh", RUN_THIGH_SWING * sw * gait, 0, 0);
  poseBone("CC_Base_R_Thigh", -RUN_THIGH_SWING * sw * gait, 0, 0);
  poseBone("CC_Base_L_Calf", Math.max(0, -RUN_CALF_TUCK * sw) * gait, 0, 0);
  poseBone("CC_Base_R_Calf", Math.max(0, RUN_CALF_TUCK * sw) * gait, 0, 0);
  // torso twist/arch + a forward lean into the sprint
  poseBone("CC_Base_Spine02", RUN_SPINE_ARCH * gait - RUN_LEAN_MAX * gait, -RUN_SPINE_TWIST * sw * gait, 0);

  return sw;
}
